import "./Content.css"
function Content(){
    return(
        <>
            <div className="cont">
                <p><h1>Mango – The King of Summer Fruits</h1>When the scorching summer sun takes over, there’s nothing more delightful than indulging in a juicy, sweet mango. Often referred to as the ‘King of Fruits,’ mangoes are loved by people of all ages. Their luscious texture, rich aroma, and heavenly taste make them an irresistible treat. Whether eaten fresh, blended into a smoothie, or enjoyed as a chilled mango shake, this fruit never fails to impress. Mangoes come in various varieties like Alphonso, Kesar, and Dussehri, each offering a unique flavor. Besides their deliciousness, mangoes are packed with essential vitamins like A, C, and E, boosting immunity and promoting healthy skin. The fiber content aids digestion, keeping summer stomach troubles at bay. In addition, mangoes can be used in savory dishes, chutneys, and even desserts. Their versatility and irresistible sweetness make them a staple in summer diets. Whether you enjoy them sliced, in a mango salsa, or as an ice cream flavor, mangoes truly make summer more enjoyable.</p>
                <p><h1>Orange – The Refreshing Citrus Delight</h1>Oranges are synonymous with refreshment during hot summer days. Their vibrant color and zesty flavor offer an instant energy boost, making them a must-have fruit in the sweltering heat. Oranges are naturally packed with vitamin C, which helps in strengthening the immune system and keeping seasonal illnesses at bay. Their high water content keeps the body hydrated, while the citrusy tang awakens the senses. Whether you prefer to enjoy them as a freshly squeezed juice, in fruit salads, or simply peeled and eaten, oranges provide a refreshing and rejuvenating experience. They are also known to improve skin health, thanks to their antioxidant properties that fight against free radicals. Apart from being a healthy snack, oranges add a delicious twist to summer desserts, marinades, and even cocktails. Their light, juicy nature makes them easy to digest, keeping you cool and energized. No summer is complete without the sweet and sour punch of oranges, making them an absolute favorite among citrus lovers.</p>
                <p><h1>Watermelon – The Ultimate Summer Thirst Quencher</h1> Nothing defines summer better than a big slice of chilled watermelon. With its high water content and natural sweetness, watermelon is the ultimate hydrating fruit during hot weather. Comprising over 90% water, it keeps the body refreshed and prevents dehydration. The crisp, juicy texture and mildly sweet flavor make it a perfect snack to enjoy on a scorching afternoon. Apart from being incredibly hydrating, watermelon is loaded with antioxidants like lycopene, which promote heart health and offer anti-inflammatory benefits. It’s also a great source of vitamins A and C, keeping the skin glowing and healthy. Watermelon can be enjoyed in various ways—eaten fresh, blended into a cooling juice, or added to fruit salads. Some even freeze watermelon slices for a refreshing popsicle-like treat. Its naturally sweet and hydrating nature makes it a go-to fruit for beach trips, picnics, and poolside snacks. If you’re looking for a delicious and healthy way to beat the heat, watermelon is undoubtedly the perfect summer fruit to keep you refreshed and energized.</p>
            </div>
        </>
    )
}
export default Content